client_config_backend: file
client_config:
    client_id: 733119250601-01sonjtdar2i0olkkg5uvr2r015iehjb.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive